import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

test('per-task bandwidth waits for an acknowledged save and exposes failures', () => {
  const inspector = fs.readFileSync('src/renderer/src/components/Inspector.tsx', 'utf8')
  const store = fs.readFileSync('src/renderer/src/lib/store.ts', 'utf8')
  const handler = inspector.match(/const handleTaskBandwidth[\s\S]*?\n  \}/)
  assert.ok(handler, 'task bandwidth handler is present')
  assert.match(handler[0], /await setTaskBandwidth\(task.id, bandwidthLimit\)/)
  assert.match(handler[0], /catch \{[\s\S]*?未能保存此任务的限速/)
  assert.match(handler[0], /finally \{[\s\S]*?setSavingTaskBandwidth\(false\)/)
  assert.match(inspector, /aria-label="此任务限速"[\s\S]*?aria-busy=\{savingTaskBandwidth\}/)
  assert.match(inspector, /aria-pressed=\{active\}/)
  assert.match(inspector, /id="task-bandwidth-status"[\s\S]*?role="status"[\s\S]*?aria-live="polite"/)
  assert.match(store, /setTaskBandwidth[\s\S]*?if \(!reply\?\.ok\) throw new Error\('任务限速未保存'\)/)
})

test('per-task connection changes wait for an acknowledged save and expose failures', () => {
  const inspector = fs.readFileSync('src/renderer/src/components/Inspector.tsx', 'utf8')
  const store = fs.readFileSync('src/renderer/src/lib/store.ts', 'utf8')
  const handler = inspector.match(/const handleTaskConnections[\s\S]*?\n  \}/)
  assert.ok(handler, 'task connections handler is present')
  assert.match(handler[0], /await setTaskConnections\(task.id, connections\)/)
  assert.match(handler[0], /catch \{[\s\S]*?未能保存此任务的连接数/)
  assert.match(handler[0], /finally \{[\s\S]*?setSavingTaskConnections\(false\)/)
  assert.match(inspector, /aria-label="任务连接数"[\s\S]*?aria-busy=\{savingTaskConnections\}/)
  assert.match(inspector, /id="task-connections-status"[\s\S]*?role="status"[\s\S]*?aria-live="polite"/)
  assert.match(store, /setTaskConnections[\s\S]*?if \(!reply\?\.ok\) throw new Error\('任务连接数未保存'\)/)
})

test('task scheduling validates future input and waits for an acknowledged save', () => {
  const inspector = fs.readFileSync('src/renderer/src/components/Inspector.tsx', 'utf8')
  const store = fs.readFileSync('src/renderer/src/lib/store.ts', 'utf8')
  const handler = inspector.match(/const handleTaskSchedule[\s\S]*?\n  \}/)
  assert.ok(handler, 'task schedule handler is present')
  assert.match(handler[0], /await scheduleTask\(task.id, startAt\)/)
  assert.match(handler[0], /catch \{[\s\S]*?未能保存此任务的预约/)
  assert.match(handler[0], /finally \{[\s\S]*?setSavingTaskSchedule\(false\)/)
  assert.match(inspector, /customStartAt == null \|\| customStartAt <= Date\.now\(\)/)
  assert.match(inspector, /const handlePresetSchedule[\s\S]*?setScheduleDate\(formatScheduleDate\(task.startAt\)\)/)
  assert.match(inspector, /请输入有效的未来日期和时间。/)
  assert.match(inspector, /aria-label="定时开始"[\s\S]*?aria-busy=\{savingTaskSchedule\}/)
  assert.match(inspector, /aria-invalid=\{scheduleInputInvalid\}/)
  assert.match(inspector, /id="task-schedule-status"[\s\S]*?role="status"[\s\S]*?aria-live="polite"/)
  assert.match(store, /scheduleTask[\s\S]*?if \(!reply\?\.ok\) throw new Error\('任务预约未保存'\)/)
})

test('task deletion keeps confirmation open until the engine acknowledges it', () => {
  const inspector = fs.readFileSync('src/renderer/src/components/Inspector.tsx', 'utf8')
  const store = fs.readFileSync('src/renderer/src/lib/store.ts', 'utf8')
  const handler = inspector.match(/const handleDelete[\s\S]*?\n  \}/)
  assert.ok(handler, 'delete handler is present')
  assert.match(handler[0], /await remove\(task.id, deleteFile\)/)
  assert.match(handler[0], /setShowDeleteConfirm\(false\)[\s\S]*?onClose\(\)/)
  assert.match(handler[0], /catch \{[\s\S]*?未能从列表移除任务/)
  assert.match(handler[0], /finally \{[\s\S]*?setDeletingTask\(false\)/)
  assert.match(inspector, /role="dialog"[\s\S]*?aria-labelledby="delete-task-title"[\s\S]*?aria-busy=\{deletingTask\}/)
  assert.match(inspector, /id="task-delete-status"[\s\S]*?role="status"[\s\S]*?aria-live="polite"/)
  assert.match(store, /export async function remove[\s\S]*?if \(!reply\?\.ok\) throw new Error\('任务未删除'\)/)
})
