// AUTO-GENERATED by tools/gen-spinning-earth.mjs — do not edit by hand.
// Unified live-preview shader for the Spinning Earth effect. The Uniforms
// field order mirrors `mslArgOrder` in config.ts so the runner's generic
// uniform packer lines up. The 256x128 land mask is baked in as a `const`
// (immutable read-only lookup — NOT var<private>, which some backends
// re-initialize per fragment invocation; the runner has no texture path).

const PI: f32 = 3.14159265358979;
const TWO_PI: f32 = 6.28318530717959;
const HALF_PI: f32 = 1.5707963267949;

const EARTH_W: i32 = 256;
const EARTH_H: i32 = 128;
const EARTH_WORDS_PER_ROW: i32 = 8;

struct Uniforms {
  size:         vec2<f32>,
  time:         f32,
  speed:        f32,
  tilt:         f32,
  globeSize:    f32,
  detail:       f32,
  dotSize:      f32,
  offsetY:      f32,
  sweepSpeed:   f32,
  contourBands: f32,
  style:        f32,
  landColor:    vec4<f32>,
  oceanColor:   vec4<f32>,
  atmosphere:   vec4<f32>,
  sweepColor:   vec4<f32>,
  gridColor:    vec4<f32>,
  contourLow:   vec4<f32>,
  contourHigh:  vec4<f32>,
};
@group(0) @binding(0) var<uniform> u: Uniforms;

const EARTH_MASK = array<u32, 1024>(
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000200u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0xf387fffau, 0x0001ffffu, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x60000000u, 0xfffefffbu, 0x007fffffu, 0x00000000u, 0x00000b08u, 0x0000001cu, 0x00000000u,
    0x00000000u, 0xf0000000u, 0xfffe1fffu, 0x0003ffffu, 0x0007ff00u, 0x00000000u, 0x0000017cu, 0x00000000u,
    0x00000000u, 0x89830000u, 0xffffe3fdu, 0x0001ffffu, 0x0000ba00u, 0x00000000u, 0x00000380u, 0x00000000u,
    0x00000000u, 0xd2047c00u, 0xffff80feu, 0x0003ffffu, 0x00000800u, 0x0000c000u, 0x0000ff80u, 0x00000000u,
    0x00000000u, 0xd21fe000u, 0xffc0007fu, 0x0003ffffu, 0x00000000u, 0xc0000f00u, 0x0001ffffu, 0x0000067cu,
    0x00000000u, 0x76001f00u, 0xff0000a6u, 0x0003ffffu, 0x00000000u, 0xfc000380u, 0x0105ffffu, 0x00000000u,
    0x00000000u, 0x379fff80u, 0xfe0007ffu, 0x0000ffffu, 0x00000000u, 0xff0e00e0u, 0x0fffffffu, 0x00000078u,
    0x00078001u, 0x303ff100u, 0xfe001fffu, 0x0001ffffu, 0x00000000u, 0xffff00c0u, 0xffffffffu, 0x0001ffffu,
    0x1ffff000u, 0x7cffe2bcu, 0xfe00fe38u, 0x00007fffu, 0x007fe000u, 0xffff3800u, 0xffffffffu, 0x3ebbffffu,
    0xfffffc03u, 0xfc7bffffu, 0xfc01fe3bu, 0x00000fffu, 0x8ffff800u, 0xffeffff9u, 0xffffffffu, 0xffffffffu,
    0xfffff03fu, 0xffffffffu, 0xfc0ff03fu, 0x000000ffu, 0x9ffffc00u, 0xfff7ffffu, 0xffffffffu, 0xffffffffu,
    0xfffffe3eu, 0xffffffffu, 0xfc04fe1fu, 0x003f801fu, 0xe1fcfe00u, 0xffffffffu, 0xffffffffu, 0xffffffffu,
    0xffffe000u, 0xffffffffu, 0xf803f039u, 0x001f0007u, 0xfffe7f80u, 0xffffffffu, 0xffffffffu, 0x7fffffffu,
    0xfffff800u, 0x7fffffffu, 0xf001c200u, 0x00000003u, 0xffff9ff0u, 0xffffffffu, 0xffffffffu, 0x7fffffffu,
    0xfffffc00u, 0x1fffffffu, 0xe0003e00u, 0x00000003u, 0xffff8ff0u, 0xffffffffu, 0xffffffffu, 0x07f47fffu,
    0xfc37e800u, 0x1fffffffu, 0x00047e00u, 0x00000001u, 0xfff71ff0u, 0xffffffffu, 0xffffffffu, 0x001c3fffu,
    0xc0070000u, 0x3fffffffu, 0x000fff00u, 0x00000000u, 0xffff0f30u, 0xffffffffu, 0xffffffffu, 0x000e001fu,
    0x00018000u, 0xffffffffu, 0x000ffe01u, 0x70000000u, 0xffff8ec0u, 0xffffffffu, 0xffffffffu, 0x000f8007u,
    0x00002000u, 0xfffffffeu, 0x001ffe07u, 0x70000000u, 0xffff83c0u, 0xffffffffu, 0xffffffffu, 0x00078001u,
    0x00000000u, 0xfffffff8u, 0x007fff3fu, 0xee000000u, 0xffffffc0u, 0xffffffffu, 0xffffffffu, 0x0003800bu,
    0x00000000u, 0xfffffff0u, 0x00ffff3fu, 0xee000000u, 0xfffffff9u, 0xffffffffu, 0xffffffffu, 0x0001803fu,
    0x00000000u, 0xffffffe0u, 0x00ffffffu, 0xe2000000u, 0xfffffffdu, 0xffffffffu, 0xffffffffu, 0x0000802fu,
    0x00000000u, 0xffffffc0u, 0x008dffffu, 0x00000000u, 0xfffffffeu, 0xffffffffu, 0xffffffffu, 0x0000002fu,
    0x00000000u, 0xffffff80u, 0x03c3ffffu, 0xe0000000u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x0000002fu,
    0x00000000u, 0xffffff00u, 0x0303ffffu, 0xc0000000u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x00000027u,
    0x00000000u, 0xffffff00u, 0x001fffffu, 0x80000000u, 0xf9bfffffu, 0xffffffe7u, 0xffffffffu, 0x00000003u,
    0x00000000u, 0xffffff00u, 0x0006ffffu, 0x80000000u, 0xf81ff9ffu, 0xfffffff3u, 0xffffffffu, 0x00000021u,
    0x00000000u, 0xffffff00u, 0x00003fffu, 0xfc000000u, 0xe00ff307u, 0xffffffe3u, 0xffffffffu, 0x00000070u,
    0x00000000u, 0xffffff00u, 0x00003fffu, 0xfc000000u, 0xe38fce03u, 0xffffff87u, 0x0fffffffu, 0x00000000u,
    0x00000000u, 0xffffff00u, 0x00000fffu, 0xfc000000u, 0xfff9c840u, 0xffffffc7u, 0x0fbfffffu, 0x00000010u,
    0x00000000u, 0xffffff00u, 0x000007ffu, 0xfe000000u, 0xfff98800u, 0xffffffc7u, 0x060fffffu, 0x00000018u,
    0x00000000u, 0xfffffe00u, 0x000003ffu, 0x7c000000u, 0xfff98600u, 0xffffffcfu, 0x0c7fffffu, 0x0000000cu,
    0x00000000u, 0xfffffc00u, 0x000003ffu, 0x00000000u, 0xfe0000ffu, 0xffffffffu, 0x0c3fffffu, 0x0000000eu,
    0x00000000u, 0xfffffc00u, 0x000001ffu, 0xf8000000u, 0xfe0000ffu, 0xffffffffu, 0xc41fffffu, 0x00000003u,
    0x00000000u, 0xfffff000u, 0x000000ffu, 0xfc000000u, 0xfe0001ffu, 0xffffffffu, 0x703fffffu, 0x00000000u,
    0x00000000u, 0xffffe000u, 0x0000003fu, 0xfe000000u, 0xff47c7ffu, 0xffffffffu, 0x207fffffu, 0x00000000u,
    0x00000000u, 0xffff4000u, 0x0000003bu, 0xfe000000u, 0xffffffffu, 0xffffffffu, 0x007fffffu, 0x00000000u,
    0x00000000u, 0x0fff8000u, 0x00000060u, 0xff000000u, 0xffffffffu, 0xfffffff3u, 0x007fffffu, 0x00000000u,
    0x00000000u, 0x07fe8000u, 0x00000060u, 0xff800000u, 0xfeffffffu, 0xffffffe7u, 0x003fffffu, 0x00000000u,
    0x00000000u, 0x07fd0000u, 0x00000040u, 0xffc00000u, 0xfdffffffu, 0xfffffe0fu, 0x001fffffu, 0x00000000u,
    0x00000000u, 0x07fb0000u, 0x00000000u, 0xffe00000u, 0xf9ffffffu, 0xffff009fu, 0x004fffffu, 0x00000000u,
    0x00000000u, 0x07f00000u, 0x00000040u, 0xffe00000u, 0xfbffffffu, 0xfffe03ffu, 0x0027ffffu, 0x00000000u,
    0x00000000u, 0x07e00000u, 0x00000180u, 0xfff00000u, 0xf3ffffffu, 0xfffe03ffu, 0x0000fffeu, 0x00000000u,
    0x00000000u, 0x07e00000u, 0x00000603u, 0xfff00000u, 0xf7ffffffu, 0x3ff003ffu, 0x00004ffcu, 0x00000000u,
    0x00000000u, 0x8fc00000u, 0x00007003u, 0xfff00000u, 0xe7ffffffu, 0x0ff001ffu, 0x000067f8u, 0x00000000u,
    0x00000000u, 0xff000000u, 0x00000003u, 0xffe00000u, 0xcfffffffu, 0x07f000ffu, 0x00400ff8u, 0x00000000u,
    0x00000000u, 0xfc000000u, 0x00000001u, 0xfff00000u, 0xcfffffffu, 0x03f0003fu, 0x00601fe8u, 0x00000000u,
    0x00000000u, 0xc0000000u, 0x0000001fu, 0xfff00000u, 0xdfffffffu, 0x01e0000fu, 0x00603fc0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0000001fu, 0xfff00000u, 0xbfffffffu, 0x01e00003u, 0x00c03fc0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0000101cu, 0xfff00000u, 0x7fffffffu, 0x01e00000u, 0x00003e40u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0011fc18u, 0xffe00000u, 0xffffffffu, 0x01c0000fu, 0x01801c40u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x001ffdb0u, 0xffc00000u, 0xffffffffu, 0x02c0000fu, 0x02000440u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x003fff40u, 0xff800000u, 0xffffffffu, 0x0200000fu, 0x038000c0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x007ffe00u, 0xff000000u, 0xffffffffu, 0x02000007u, 0x03080180u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x07fffe00u, 0x5e000000u, 0xfffffff0u, 0x00000007u, 0x000c03b0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0ffffe00u, 0x00000000u, 0xffffff80u, 0x00000003u, 0x000e0360u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0fffff00u, 0x00000000u, 0xffffff80u, 0x00000001u, 0x000f83c0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x1fffff80u, 0x00000000u, 0x7fffff80u, 0x00000000u, 0x014fe3c0u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x7fffff80u, 0x00000000u, 0x3fffffc0u, 0x00000000u, 0x600fc380u, 0x00000000u,
    0x00000000u, 0x00000000u, 0xffffff80u, 0x00000000u, 0x1fffff80u, 0x00000000u, 0xc067c700u, 0x00000006u,
    0x00000000u, 0x00000000u, 0xffffff80u, 0x0000000fu, 0x1fffff00u, 0x00000000u, 0xd8660f00u, 0x0000003fu,
    0x00000000u, 0x00000000u, 0xffffffc0u, 0x0000003fu, 0x0fffff00u, 0x00000000u, 0x00200e00u, 0x000000feu,
    0x00000000u, 0x00000000u, 0xffffff80u, 0x0000007fu, 0x0ffffe00u, 0x00000000u, 0x00001800u, 0x000045fcu,
    0x00000000u, 0x00000000u, 0xffffff80u, 0x0000007fu, 0x0ffffe00u, 0x00000000u, 0x0001f000u, 0x000001fcu,
    0x00000000u, 0x00000000u, 0xffffff00u, 0x0000007fu, 0x0ffffe00u, 0x00000000u, 0x02000000u, 0x00000330u,
    0x00000000u, 0x00000000u, 0xfffffe00u, 0x0000003fu, 0x1ffffc00u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0xfffffe00u, 0x0000001fu, 0x1ffffc00u, 0x00000000u, 0xe0000000u, 0x00000020u,
    0x00000000u, 0x00000000u, 0xfffffc00u, 0x0000001fu, 0x1ffffe00u, 0x0000000cu, 0xf0000000u, 0x00000021u,
    0x00000000u, 0x00000000u, 0xfffffc00u, 0x0000000fu, 0x1ffffe00u, 0x0000000cu, 0xf6000000u, 0x00000061u,
    0x00000000u, 0x00000000u, 0xfffff800u, 0x0000000fu, 0x1fffff00u, 0x0000000fu, 0xff000000u, 0x000000f3u,
    0x00000000u, 0x00000000u, 0xffffe000u, 0x0000000fu, 0x87ffff00u, 0x00000007u, 0xff800000u, 0x400000ffu,
    0x00000000u, 0x00000000u, 0xffffc000u, 0x0000000fu, 0x83fffe00u, 0x00000007u, 0xffc00000u, 0x000000ffu,
    0x00000000u, 0x00000000u, 0xffffc000u, 0x0000000fu, 0x81fffe00u, 0x00000007u, 0xfff00000u, 0x000003ffu,
    0x00000000u, 0x00000000u, 0xffffc000u, 0x00000007u, 0x81fffc00u, 0x00000003u, 0xfffc0000u, 0x000003ffu,
    0x00000000u, 0x00000000u, 0xffffc000u, 0x00000001u, 0x81fffc00u, 0x00000003u, 0xfffe0000u, 0x00000fffu,
    0x00000000u, 0x00000000u, 0x7fffc000u, 0x00000000u, 0x81fffc00u, 0x00000003u, 0xfffe0000u, 0x00000fffu,
    0x00000000u, 0x00000000u, 0x3fffc000u, 0x00000000u, 0x00fff800u, 0x00000000u, 0xfffe0000u, 0x00001fffu,
    0x00000000u, 0x00000000u, 0x3fffe000u, 0x00000000u, 0x007ff800u, 0x00000000u, 0xfffe0000u, 0x00001fffu,
    0x00000000u, 0x00000000u, 0x1fffe000u, 0x00000000u, 0x007ff000u, 0x00000000u, 0xfffe0000u, 0x00001fffu,
    0x00000000u, 0x00000000u, 0x0fffe000u, 0x00000000u, 0x003ff000u, 0x00000000u, 0xfffc0000u, 0x00001fffu,
    0x00000000u, 0x00000000u, 0x07ffe000u, 0x00000000u, 0x001fe000u, 0x00000000u, 0xfffc0000u, 0x00001fffu,
    0x00000000u, 0x00000000u, 0x07ffe000u, 0x00000000u, 0x000fe000u, 0x00000000u, 0x81fc0000u, 0x00000fffu,
    0x00000000u, 0x00000000u, 0x03ffe000u, 0x00000000u, 0x0000e000u, 0x00000000u, 0x001c0000u, 0x00000ffdu,
    0x00000000u, 0x00000000u, 0x00fff000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x080007f8u,
    0x00000000u, 0x00000000u, 0x00fff000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x100007f8u,
    0x00000000u, 0x00000000u, 0x007ff000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x70000160u,
    0x00000000u, 0x00000000u, 0x000ff000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x30000000u,
    0x00000000u, 0x00000000u, 0x0003f800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0c000380u,
    0x00000000u, 0x00000000u, 0x0003f800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x06000180u,
    0x00000000u, 0x00000000u, 0x0003f000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x03000000u,
    0x00000000u, 0x00000000u, 0x0000f800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x03800000u,
    0x00000000u, 0x00000000u, 0x0001f800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0001fc00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0000f800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00407800u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00007000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0000e000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00400000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x000c0000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00070000u, 0x00000000u, 0x00000000u, 0xc00000f0u, 0xf783ffffu, 0x0000003fu,
    0x00000000u, 0x00000000u, 0x00030000u, 0x00000000u, 0xc0000000u, 0xff03ffffu, 0xffffffffu, 0x000001ffu,
    0x00000000u, 0x00000000u, 0x000f6000u, 0x00000000u, 0xf7800000u, 0xffc1ffffu, 0xffffffffu, 0x0003ffffu,
    0x00000000u, 0x00000000u, 0x000fe000u, 0x28000000u, 0xfffffffeu, 0xfff9ffffu, 0xffffffffu, 0x00ffffffu,
    0x00000000u, 0x00000000u, 0x001f4800u, 0xff800000u, 0xffffffffu, 0xfffeffffu, 0xffffffffu, 0x01ffffffu,
    0x00000000u, 0xff800240u, 0x001fffffu, 0xffe00000u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x003fffffu,
    0xf0000000u, 0xffffffffu, 0x0007ffffu, 0xfff80000u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x000fffffu,
    0xff000000u, 0xffffffffu, 0x00007fffu, 0xfffff800u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x000fffffu,
    0xffff0000u, 0xffffffffu, 0xe00007ffu, 0xffffff80u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x005fffffu,
    0xfff03000u, 0xffffffffu, 0xf00063ffu, 0xfffffe83u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x0003ffffu,
    0xfff80000u, 0xffffffffu, 0x3c107fffu, 0xfffffff0u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x0003ffffu,
    0xfff80000u, 0xffffffffu, 0x7e0bffffu, 0xfffffffeu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x000fffffu,
    0xfffffa00u, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0x0fffffffu,
    0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu,
    0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu,
    0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu,
    0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu, 0xffffffffu,
);

fn earthLandPoint(lat: f32, lon: f32) -> bool {
  let uu = fract((lon + PI) / TWO_PI);
  let vv = clamp((HALF_PI - lat) / PI, 0.0, 0.99999);
  let col = clamp(i32(uu * f32(EARTH_W)), 0, EARTH_W - 1);
  let row = clamp(i32(vv * f32(EARTH_H)), 0, EARTH_H - 1);
  let widx = row * EARTH_WORDS_PER_ROW + (col / 32);
  let bit = u32(col % 32);
  return ((EARTH_MASK[widx] >> bit) & 1u) != 0u;
}

fn earthLandHits(lat: f32, lon: f32, dLat: f32, dLon: f32) -> i32 {
  var hits = 0;
  for (var j = -1; j <= 1; j = j + 1) {
    for (var i = -1; i <= 1; i = i + 1) {
      if (earthLandPoint(lat + f32(j) * dLat * 0.4, lon + f32(i) * dLon * 0.4)) {
        hits = hits + 1;
      }
    }
  }
  return hits;
}

fn earthHash21(p: vec2<f32>) -> f32 {
  return fract(sin(dot(p, vec2<f32>(127.1, 311.7))) * 43758.5453123);
}

fn earthValueNoise(p: vec2<f32>) -> f32 {
  let i = floor(p);
  let f = fract(p);
  let w = f * f * (3.0 - 2.0 * f);
  let a = earthHash21(i);
  let b = earthHash21(i + vec2<f32>(1.0, 0.0));
  let c = earthHash21(i + vec2<f32>(0.0, 1.0));
  let d = earthHash21(i + vec2<f32>(1.0, 1.0));
  return mix(mix(a, b, w.x), mix(c, d, w.x), w.y);
}

fn earthFbm(p0: vec2<f32>) -> f32 {
  var p = p0;
  var v = 0.0;
  var amp = 0.5;
  for (var i = 0; i < 5; i = i + 1) {
    v = v + amp * earthValueNoise(p);
    p = p * 2.02;
    amp = amp * 0.5;
  }
  return v;
}

struct EarthHit {
  hit:   bool,
  rr:    f32,
  disk:  vec2<f32>,
  viewN: vec3<f32>,
  lat:   f32,
  lon:   f32,
};

fn earthProject(pos: vec2<f32>, size: vec2<f32>, angle: f32, tilt: f32, radiusFrac: f32, offsetY: f32) -> EarthHit {
  var h: EarthHit;
  // offsetY slides the globe vertically: +1 drops its centre to the bottom
  // edge, -1 lifts it to the top, 0 = centred.
  let center = vec2<f32>(0.5 * size.x, 0.5 * size.y + offsetY * 0.5 * size.y);
  let R = radiusFrac * min(size.x, size.y);
  let p = (pos - center) / R;
  let rr = dot(p, p);
  h.disk = p;
  h.rr = rr;
  h.hit = rr <= 1.0;
  if (!h.hit) {
    h.viewN = vec3<f32>(p.x, -p.y, 0.0);
    h.lat = 0.0;
    h.lon = 0.0;
    return h;
  }
  let V = vec3<f32>(p.x, -p.y, sqrt(max(0.0, 1.0 - rr)));
  h.viewN = V;
  let ct = cos(tilt);
  let st = sin(tilt);
  let T = vec3<f32>(V.x, ct * V.y + st * V.z, -st * V.y + ct * V.z);
  let ca = cos(angle);
  let sa = sin(angle);
  let M = vec3<f32>(ca * T.x - sa * T.z, T.y, sa * T.x + ca * T.z);
  h.lat = asin(clamp(M.y, -1.0, 1.0));
  h.lon = atan2(M.x, M.z);
  return h;
}

fn radarBehind(pixAng: f32, sweepAng: f32) -> f32 {
  var d = sweepAng - pixAng;
  d = d - TWO_PI * floor(d / TWO_PI);
  return d;
}

// Tonal curve reused from the original B&W ramp (6 eased segments). Returns a
// single 0..1 luminance value; contourThermal maps it onto the low→high colour
// gradient so the style is colourable while keeping the same elevation banding.
fn contourTone(t0: f32) -> f32 {
  let t = clamp(t0, 0.0, 1.0);
  let x = t * 6.0;
  let s0 = 0.07; let s1 = 0.21; let s2 = 0.38;
  let s3 = 0.55; let s4 = 0.72; let s5 = 0.88; let s6 = 1.0;
  if (x < 1.0) { return mix(s0, s1, smoothstep(0.0, 1.0, x)); }
  if (x < 2.0) { return mix(s1, s2, smoothstep(0.0, 1.0, x - 1.0)); }
  if (x < 3.0) { return mix(s2, s3, smoothstep(0.0, 1.0, x - 2.0)); }
  if (x < 4.0) { return mix(s3, s4, smoothstep(0.0, 1.0, x - 3.0)); }
  if (x < 5.0) { return mix(s4, s5, smoothstep(0.0, 1.0, x - 4.0)); }
  return mix(s5, s6, smoothstep(0.0, 1.0, x - 5.0));
}

fn contourThermal(t0: f32, lo: vec3<f32>, hi: vec3<f32>) -> vec3<f32> {
  return mix(lo, hi, contourTone(t0));
}

fn contourField(lat: f32, lon: f32, drift: f32) -> f32 {
  let q = vec2<f32>(lon * (1.0 / PI), lat * (2.0 / PI));
  let base = q * 2.7 + vec2<f32>(11.3, 4.7);
  var f = earthFbm(base + vec2<f32>(drift, -0.5 * drift));
  f = f + 0.45 * earthFbm(base * 2.13 + vec2<f32>(-drift * 1.7, 23.0));
  f = f / 1.45;
  return clamp(f, 0.0, 1.0);
}

fn knee(c: vec3<f32>, k: f32) -> vec3<f32> {
  let over = max(c - vec3<f32>(k), vec3<f32>(0.0));
  return min(c, vec3<f32>(k)) + (1.0 - k) * (vec3<f32>(1.0) - exp(-over / (1.0 - k)));
}

fn spinningEarthAnim(uv01: vec2<f32>) -> vec4<f32> {
  let size = u.size;
  let pos = uv01 * size;
  let angle = u.time * u.speed;
  let e = earthProject(pos, size, angle, u.tilt, u.globeSize, u.offsetY);
  let p = e.disk;
  let rr = e.rr;
  let rad = sqrt(max(rr, 0.0));

  // --- shared dotted graticule (straight-line: derivative calls are legal) ---
  let bands = max(1.0, round(u.detail));
  let dLat = PI / bands;
  let lat = e.lat;
  let lon = e.lon;
  let latNode = round(lat / dLat) * dLat;
  let ring = max(1.0, round(TWO_PI * cos(latNode) / dLat));
  let dLon = TWO_PI / ring;
  let lonNode = round(lon / dLon) * dLon;
  var dLonOff = lon - lonNode;
  dLonOff = dLonOff - TWO_PI * round(dLonOff / TWO_PI);
  let na = (lat - latNode) / dLat;
  let nb = dLonOff / dLon;
  // Round dot (dotRound == 2): length(na, nb) — equal to the MSL pow() form,
  // far cheaper than three pow() calls per pixel.
  let dist = sqrt(na * na + nb * nb);
  let aaw = max(fwidth(dist) * 1.1, 0.012);
  let dotCore = 1.0 - smoothstep(u.dotSize - aaw, u.dotSize + aaw, dist);
  let poleFade = smoothstep(HALF_PI, HALF_PI - 2.0 * dLat, abs(latNode));
  let dotBase = dotCore * poleFade;

  let s = i32(u.style + 0.5);
  var outc = vec3<f32>(0.0);

  if (s == 0) {
    // ---------------------------- Metal Dots ----------------------------
    let dotMask = dotBase * smoothstep(1.0, 0.92, rr);
    let kLight = normalize(vec3<f32>(-0.45, 0.55, 0.70));
    let kLand = u.landColor.rgb;
    let kOcean = u.oceanColor.rgb;
    let kRim = u.atmosphere.rgb;
    if (e.hit) {
      let V = e.viewN;
      let land = earthLandHits(latNode, lonNode, dLat, dLon) >= 4;
      let Hh = normalize(kLight + vec3<f32>(0.0, 0.0, 1.0));
      let diff = max(dot(V, kLight), 0.0);
      let spec = pow(max(dot(V, Hh), 0.0), 34.0);
      let rim = pow(1.0 - V.z, 3.0);
      let base = select(kOcean, kLand, land);
      let lvl = select(0.42, 1.0, land);
      let specLvl = select(0.5, 1.0, land);
      // On water, tint the specular toward the ocean colour (instead of pure
      // white) so changing Ocean visibly shifts the globe; land keeps a white
      // chrome highlight.
      let specTint = select(mix(vec3<f32>(1.0), base, 0.6), vec3<f32>(1.0), land);
      let lit = base * (0.18 + 0.92 * diff) * lvl
              + specTint * (spec * 1.25 * specLvl)
              + kRim * (rim * 0.55) * lvl;
      outc = lit * dotMask;
      let edge = smoothstep(0.92, 1.0, rr) * smoothstep(1.02, 1.0, rr);
      outc = outc + kRim * (edge * 0.16 * (0.4 + 0.6 * diff));
    } else if (rr < 1.18 * 1.18) {
      let d = sqrt(rr) - 1.0;
      let halo = exp(-d * 11.0) * 0.16;
      let diff = max(dot(normalize(vec3<f32>(p.x, -p.y, 0.35)), kLight), 0.0);
      outc = kRim * (halo * (0.35 + 0.65 * diff));
    }
    outc = knee(outc, 0.75);
  } else if (s == 1) {
    // ---------------------------- Radar Ping ----------------------------
    let green = u.sweepColor.rgb;
    let greenHi = mix(green, vec3<f32>(1.0), 0.45);
    let gridG = u.gridColor.rgb;
    var sweep = u.time * u.sweepSpeed;
    sweep = sweep - TWO_PI * floor(sweep / TWO_PI);
    var intensity = 0.0;
    var tint = green;
    if (e.hit) {
      let dotMask = dotBase * smoothstep(1.0, 0.94, rr);
      let hits = earthLandHits(latNode, lonNode, dLat, dLon);  // sample once
      let land = hits >= 4;
      let cover = f32(hits) / 9.0;
      let cellAng = atan2(p.y, p.x);
      let bh = radarBehind(cellAng, sweep);
      let decay = select(2.7, 1.05, land);
      let trail = exp(-bh * decay);
      let lip = smoothstep(0.22, 0.0, bh);
      let baseGlow = select(0.085, 0.16, land);
      let landBoost = select(0.30, 0.85 + 0.6 * cover, land);
      let ping = (trail * 0.9 + lip * 1.4) * landBoost;
      intensity = (baseGlow + ping) * dotMask;
      if (land) {
        let blipKey = earthHash21(vec2<f32>(latNode * 7.3 + 11.0, lonNode * 5.1 + 3.0));
        let isTarget = step(0.82, blipKey);
        var flash = exp(-bh * 1.6) * (0.6 + 0.4 * sin(u.time * 9.0 + blipKey * 30.0));
        flash = max(flash, 0.0);
        intensity = intensity + isTarget * flash * 1.6 * dotMask;
        tint = mix(tint, greenHi, isTarget * lip);
      }
      tint = mix(tint, greenHi, clamp(intensity * 0.7, 0.0, 1.0));
    }
    // scope overlay (masks gate it, so no per-pixel branch is needed)
    let scopeR = 1.06;
    let scopeMask = smoothstep(scopeR, scopeR - 0.02, rad);
    let ringPhase = rad * 4.0;
    let rline = abs(fract(ringPhase + 0.5) - 0.5) * 2.0;
    let rw = max(fwidth(ringPhase) * 1.4, 0.02);
    var grid = smoothstep(rw, 0.0, rline) * 0.5;
    grid = grid + smoothstep(0.012, 0.0, abs(rad - (scopeR - 0.01))) * 0.8;
    let cw = max(fwidth(p.x), fwidth(p.y)) * 1.2 + 0.004;
    var cross = smoothstep(cw, 0.0, abs(p.x)) + smoothstep(cw, 0.0, abs(p.y));
    cross = cross + 0.5 * smoothstep(cw, 0.0, abs(p.x - p.y));
    cross = cross + 0.5 * smoothstep(cw, 0.0, abs(p.x + p.y));
    grid = grid + clamp(cross, 0.0, 1.0) * 0.32;
    grid = grid * scopeMask;
    let pixAng = atan2(p.y, p.x);
    let bh2 = radarBehind(pixAng, sweep);
    let armLine = smoothstep(0.05, 0.0, bh2);
    let armWedge = exp(-bh2 * 2.2) * 0.5;
    let armGlow = (armLine * 0.9 + armWedge) * scopeMask * smoothstep(0.0, 0.12, rad);
    var col = tint * intensity;
    col = col + gridG * grid;
    col = col + green * armGlow * 0.7;
    let lum = dot(col, vec3<f32>(0.3, 0.6, 0.1));
    col = col + green * (lum * lum * 0.6);
    col = col * (0.92 + 0.08 * sin(pos.y * 2.2));
    col = col * (1.0 - smoothstep(0.55, 1.15, rad) * 0.55);
    col = col + green * 0.015 * scopeMask;
    outc = max(col, vec3<f32>(0.004, 0.012, 0.006) * smoothstep(1.6, 0.0, rad));
  } else {
    // ---------------------------- Contour Mono ----------------------------
    let cLo = u.contourLow.rgb;
    let cHi = u.contourHigh.rgb;
    let dotMask = dotBase * smoothstep(1.0, 0.93, rr);
    let drift = u.time * 0.045;
    let cover = f32(earthLandHits(latNode, lonNode, dLat, dLon)) / 9.0;
    var heat = contourField(latNode, lonNode, drift);
    heat = heat + 0.46 * cover - 0.30 * (1.0 - cover);
    heat = heat + 0.08 * cos(latNode);
    heat = clamp(heat, 0.0, 1.0);
    let bandPos = heat * u.contourBands;
    let lineAA = max(fwidth(bandPos), 0.04);
    if (e.hit) {
      let N = normalize(e.viewN);
      var col = contourThermal(heat, cLo, cHi);
      let tri = abs(fract(bandPos) - 0.5) * 2.0;
      let onLine = 1.0 - smoothstep(0.0, lineAA * 4.0, tri);
      let lineTint = mix(col, cHi, 0.45);
      col = mix(col, lineTint, onLine * 0.55);
      let L = normalize(vec3<f32>(-0.35, 0.45, 0.82));
      let diff = 0.55 + 0.45 * max(dot(N, L), 0.0);
      col = col * diff;
      let hot = smoothstep(0.72, 1.0, heat);
      col = col + contourThermal(heat, cLo, cHi) * (hot * 0.85);
      outc = col * dotMask;
      let edge = smoothstep(0.93, 1.0, rr) * smoothstep(1.015, 1.0, rr);
      outc = outc + mix(cLo, cHi, 0.15) * (edge * 0.25);
    } else if (rr < 1.26 * 1.26) {
      let d = sqrt(rr) - 1.0;
      let halo = exp(-d * 9.0) * 0.16;
      outc = mix(cLo, cHi, 0.06) * halo;
    }
    outc = knee(outc, 0.80);
  }

  return vec4<f32>(clamp(outc, vec3<f32>(0.0), vec3<f32>(1.0)), 1.0);
}
