import AVFoundation
import XCTest
@testable import NDMCore
@testable import NDMEngine

/// Exercises real on-device transcription against speech generated by `say`.
/// Nothing here touches the network, so it belongs in the default suite; it skips
/// on systems without the framework rather than failing.
final class SpeechTranscriptionEngineTests: XCTestCase {
    private func requireEngine() throws -> Any {
        guard #available(macOS 26, *) else {
            throw XCTSkip("on-device transcription requires macOS 26 or later")
        }
        return 0
    }

    /// Synthesize speech with `say`. Returns nil when the requested voice is not
    /// installed, so a missing voice skips instead of failing.
    private func synthesize(_ text: String, voice: String?) throws -> URL? {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ndm-speech-\(UUID().uuidString).aiff")
        var arguments: [String] = []
        if let voice { arguments += ["-v", voice] }
        arguments += ["-o", url.path, text]

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/say")
        process.arguments = arguments
        process.standardError = Pipe()
        process.standardOutput = Pipe()
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0,
              let size = try? FileManager.default.attributesOfItem(atPath: url.path)[.size]
                  as? NSNumber,
              size.int64Value > 0
        else {
            try? FileManager.default.removeItem(at: url)
            return nil
        }
        return url
    }

    func testEnvironmentReportsWhatTheSystemActuallyOffers() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        let environment = await SpeechTranscriptionEngine.environment()
        XCTAssertTrue(environment.isSupportedByOS)
        XCTAssertFalse(
            environment.supportedLocaleIdentifiers.isEmpty,
            "a system with the framework must support at least one language"
        )
        // Installed is a subset of supported; anything else means the two lists
        // were read from different places.
        let supported = Set(environment.supportedLocaleIdentifiers.map(
            TranscriptionWorkflow.normalized
        ))
        for installed in environment.installedLocaleIdentifiers {
            XCTAssertTrue(
                supported.contains(TranscriptionWorkflow.normalized(installed)),
                "\(installed) is installed but not reported as supported"
            )
        }
    }

    /// The seam between C1-1's pure rules and the real system: a plan built from
    /// the live environment must be actionable, not merely well-formed.
    func testLivePlanForAChineseSourceIsActionable() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        let environment = await SpeechTranscriptionEngine.environment()
        let media = FileManager.default.temporaryDirectory
            .appendingPathComponent("plan-probe.mp4")
        let decision = TranscriptionWorkflow.decide(
            fileURL: media,
            pageURL: "https://www.bilibili.com/video/BV1",
            environment: environment,
            fileExists: { _ in true }
        )
        let plan = try XCTUnwrap(decision.plan, "expected a workable plan")
        XCTAssertTrue(
            environment.supportedLocaleIdentifiers.contains(plan.localeIdentifier),
            "the planner must hand back an identifier the system actually reported"
        )
    }

    func testTranscribesChineseSpeech() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        guard let audio = try synthesize(
            "这是一段中文测试语音，用来验证本地转写是否可用。",
            voice: "Meijia"
        ) else {
            throw XCTSkip("no Chinese voice installed for `say`")
        }
        defer { try? FileManager.default.removeItem(at: audio) }

        let engine = SpeechTranscriptionEngine()
        let environment = await SpeechTranscriptionEngine.environment()
        guard let locale = TranscriptionWorkflow.match(
            tag: "zh-Hans",
            in: environment.supportedLocaleIdentifiers
        ) else {
            throw XCTSkip("this system cannot transcribe Chinese")
        }

        var lastFraction = -1.0
        let segments = try await engine.transcribe(
            fileURL: audio,
            localeIdentifier: locale,
            onProgress: { lastFraction = $0 }
        )

        XCTAssertFalse(segments.isEmpty, "expected recognised speech")
        let joined = segments.map(\.text).joined()
        XCTAssertTrue(
            joined.contains("中文") || joined.contains("测试"),
            "recognised text was \(joined.debugDescription)"
        )
        XCTAssertGreaterThanOrEqual(lastFraction, 0, "progress must come from the analyzer")
    }

    func testTranscribesEnglishSpeech() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        guard let audio = try synthesize(
            "The quick brown fox jumps over the lazy dog.",
            voice: nil
        ) else {
            throw XCTSkip("`say` produced no audio")
        }
        defer { try? FileManager.default.removeItem(at: audio) }

        let engine = SpeechTranscriptionEngine()
        let environment = await SpeechTranscriptionEngine.environment()
        guard let locale = TranscriptionWorkflow.match(
            tag: "en",
            in: environment.supportedLocaleIdentifiers
        ) else {
            throw XCTSkip("this system cannot transcribe English")
        }

        let segments = try await engine.transcribe(fileURL: audio, localeIdentifier: locale)
        XCTAssertFalse(segments.isEmpty)
        let joined = segments.map(\.text).joined(separator: " ").lowercased()
        XCTAssertTrue(
            joined.contains("fox") || joined.contains("dog"),
            "recognised text was \(joined.debugDescription)"
        )
    }

    /// Timings feed subtitle generation directly, so a non-monotonic or negative
    /// range would produce a file that no player can follow.
    func testTimingsAreMonotonicAndNonNegative() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        guard let audio = try synthesize(
            "One. Two. Three. Four. Five. Six. Seven. Eight.",
            voice: nil
        ) else {
            throw XCTSkip("`say` produced no audio")
        }
        defer { try? FileManager.default.removeItem(at: audio) }

        let environment = await SpeechTranscriptionEngine.environment()
        guard let locale = TranscriptionWorkflow.match(
            tag: "en",
            in: environment.supportedLocaleIdentifiers
        ) else {
            throw XCTSkip("this system cannot transcribe English")
        }
        let segments = try await SpeechTranscriptionEngine().transcribe(
            fileURL: audio,
            localeIdentifier: locale
        )
        XCTAssertFalse(segments.isEmpty)
        var previousEnd = -1.0
        for segment in segments {
            XCTAssertGreaterThanOrEqual(segment.start, 0)
            XCTAssertGreaterThanOrEqual(segment.end, segment.start)
            XCTAssertGreaterThanOrEqual(
                segment.start,
                previousEnd - 0.001,
                "segments must not go backwards"
            )
            previousEnd = segment.end
        }
    }

    /// The whole point of C1-2 taking a neutral type: real engine output must flow
    /// straight into subtitle serialization.
    func testRealSegmentsProduceValidSubRip() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        guard let audio = try synthesize(
            "这是第一句话。这是第二句话。这是第三句话。",
            voice: "Meijia"
        ) else {
            throw XCTSkip("no Chinese voice installed for `say`")
        }
        defer { try? FileManager.default.removeItem(at: audio) }

        let environment = await SpeechTranscriptionEngine.environment()
        guard let locale = TranscriptionWorkflow.match(
            tag: "zh-Hans",
            in: environment.supportedLocaleIdentifiers
        ) else {
            throw XCTSkip("this system cannot transcribe Chinese")
        }
        let segments = try await SpeechTranscriptionEngine().transcribe(
            fileURL: audio,
            localeIdentifier: locale
        )
        let srt = TranscriptDocument.srt(from: segments)
        XCTAssertFalse(srt.isEmpty)
        XCTAssertTrue(srt.hasPrefix("1\n"))
        XCTAssertTrue(srt.contains(" --> "))
        XCTAssertTrue(srt.hasSuffix("\n\n"))
        XCTAssertFalse(
            TranscriptDocument.plainText(from: segments).isEmpty,
            "a readable transcript must come out of the same segments"
        )
    }

    func testUnreadableFileFailsWithoutHanging() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        let bogus = FileManager.default.temporaryDirectory
            .appendingPathComponent("ndm-not-audio-\(UUID().uuidString).mp4")
        try Data("this is not audio".utf8).write(to: bogus)
        defer { try? FileManager.default.removeItem(at: bogus) }

        do {
            _ = try await SpeechTranscriptionEngine().transcribe(
                fileURL: bogus,
                localeIdentifier: "en_US"
            )
            XCTFail("a file that is not audio must not report success")
        } catch let failure as SpeechTranscriptionEngine.Failure {
            guard case .unreadableAudio = failure else {
                return XCTFail("expected unreadableAudio, got \(failure)")
            }
        }
    }

    func testCancellationStopsBeforeReturningSegments() async throws {
        _ = try requireEngine()
        guard #available(macOS 26, *) else { return }

        guard let audio = try synthesize(
            "One two three four five six seven eight nine ten eleven twelve.",
            voice: nil
        ) else {
            throw XCTSkip("`say` produced no audio")
        }
        defer { try? FileManager.default.removeItem(at: audio) }

        let token = CancelToken()
        token.cancel()
        do {
            _ = try await SpeechTranscriptionEngine().transcribe(
                fileURL: audio,
                localeIdentifier: "en_US",
                cancelToken: token
            )
            XCTFail("a cancelled run must not return segments")
        } catch let failure as SpeechTranscriptionEngine.Failure {
            XCTAssertEqual(failure, .cancelled)
        }
    }
}
