#!/usr/bin/env python3
"""Loopback-only, read-only SFTP fixture. Requires Paramiko 4.0.0 in a QA venv.

Serves only generated bytes at /fixture.bin. Never reads user-selected paths.
Writes connection/read offsets (without credentials) to events.jsonl.
API reference: https://docs.paramiko.org/en/stable/api/sftp.html
"""
import argparse
import base64
import hashlib
import hmac
import json
import logging
import os
import secrets
import signal
import socket
import stat
import tempfile
import threading
import time
from pathlib import Path

import paramiko

parser = argparse.ArgumentParser()
parser.add_argument('--bytes', type=int, default=2 * 1024 * 1024)
parser.add_argument('--delay', type=float, default=0.01)
args = parser.parse_args()
if not 0 <= args.bytes <= 64 * 1024 * 1024 or not 0 <= args.delay <= 1:
    raise SystemExit('Invalid fixture size or delay')
root = Path(tempfile.mkdtemp(prefix='ndm-sftp-fixture-'))
os.chmod(root, 0o700)
payload = bytes(index % 251 for index in range(args.bytes))
(root / 'fixture.bin').write_bytes(payload)
key = paramiko.RSAKey.generate(2048)
username, password = 'ndm-fixture', secrets.token_hex(16)
pin = 'SHA256:' + base64.b64encode(hashlib.sha256(key.asbytes()).digest()).decode().rstrip('=')
stop = threading.Event()
lock = threading.Lock()
transports = []
logging.getLogger('paramiko').setLevel(logging.CRITICAL)


def event(kind, **values):
    with lock, (root / 'events.jsonl').open('a') as output:
        output.write(json.dumps(dict(event=kind, **values)) + '\n')


def attributes():
    result = paramiko.SFTPAttributes()
    result.st_size = len(payload)
    result.st_mode = stat.S_IFREG | 0o444
    result.st_uid = result.st_gid = 0
    result.st_atime = result.st_mtime = 1700000000
    return result


class Handle(paramiko.SFTPHandle):
    def stat(self):
        return attributes()

    def read(self, offset, length):
        if offset < 0 or length < 0 or length > 1024 * 1024:
            return paramiko.SFTP_FAILURE
        if args.delay:
            time.sleep(args.delay)
        result = payload[offset:offset + length]
        event('read', offset=offset, length=len(result))
        return result


class Files(paramiko.SFTPServerInterface):
    def canonicalize(self, path):
        return path if path.startswith('/') else '/' + path

    def stat(self, path):
        return attributes() if path == '/fixture.bin' else paramiko.SFTP_NO_SUCH_FILE

    lstat = stat

    def open(self, path, flags, attr):
        if path != '/fixture.bin' or flags & (os.O_WRONLY | os.O_RDWR | os.O_CREAT | os.O_TRUNC | os.O_APPEND):
            return paramiko.SFTP_PERMISSION_DENIED
        event('open')
        return Handle()


class Authentication(paramiko.ServerInterface):
    def check_auth_password(self, user, secret):
        accepted = hmac.compare_digest(user, username) and hmac.compare_digest(secret, password)
        event('authentication', accepted=accepted)
        return paramiko.AUTH_SUCCESSFUL if accepted else paramiko.AUTH_FAILED

    def get_allowed_auths(self, user):
        return 'password'

    def check_channel_request(self, kind, chanid):
        return paramiko.OPEN_SUCCEEDED if kind == 'session' else paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED


def serve(connection):
    transport = paramiko.Transport(connection)
    with lock:
        transports.append(transport)
    try:
        transport.add_server_key(key)
        transport.set_subsystem_handler('sftp', paramiko.SFTPServer, Files)
        transport.start_server(server=Authentication())
        while transport.is_active() and not stop.wait(0.1):
            pass
    except (OSError, EOFError, paramiko.SSHException):
        event('connection_closed')
    finally:
        transport.close()
        with lock:
            transports.remove(transport)


listener = socket.socket()
listener.bind(('127.0.0.1', 0))
listener.listen(8)
listener.settimeout(0.25)
metadata = dict(root=str(root), pid=os.getpid(), port=listener.getsockname()[1],
                url=f'sftp://127.0.0.1:{listener.getsockname()[1]}/fixture.bin',
                username=username, password=password, hostKeySHA256=pin,
                bytes=len(payload), sha256=hashlib.sha256(payload).hexdigest())
(root / 'metadata.json').write_text(json.dumps(metadata))
os.chmod(root / 'metadata.json', 0o600)
print(json.dumps(dict(metadataPath=str(root / 'metadata.json'))), flush=True)
signal.signal(signal.SIGTERM, lambda *_: stop.set())
signal.signal(signal.SIGINT, lambda *_: stop.set())
try:
    while not stop.is_set():
        try:
            connection, _ = listener.accept()
        except socket.timeout:
            continue
        event('connection')
        threading.Thread(target=serve, args=(connection,), daemon=True).start()
finally:
    listener.close()
    with lock:
        owned_transports = list(transports)
    for transport in owned_transports:
        transport.close()
    event('stopped')
    # Artifacts remain for the invoking QA runner to verify and remove.
